var bankName;
console.log("Value of variable =>", bankName);
bankName = "SBI Bank";
console.log("Bank Name =>", bankName);
console.log("Type of Variable Bank Name =>", typeof bankName);
var mark = '90%';
console.log("mark =>", mark);
console.log("Type of Variable mark =>", typeof mark);
var isWorking;
console.log("value of Variable isWorking=>", isWorking);
isWorking = false;
console.log("Are You Working => ", isWorking);
console.log("Type Of Variable isWorking =>", typeof isWorking);
var totalCount = "Hundred and Seven";
console.log("Total Count +>", totalCount);
console.log("Type Of Variable totalCount =>", typeof totalCount);
totalCount = 107;
console.log("Total Count =>", totalCount);
console.log("Type of Variable total Count =>", typeof totalCount);